siteName: Institut pour la Paix
tagline: La paix comme objet d'étude
logo: /uploads/wp-import/INSTITUT-rvb.png
favicon: /uploads/wp-import/cropped-FILET-RVB-03-192x192.webp
description: >
  L'Institut Pour la Paix est un laboratoire à l'interface de la recherche
  universitaire et de la pratique, qui propose une façon innovante de produire de
  la connaissance sur la paix.
email: contact@institutpourlapaix.org
presentationVideoUrl: https://youtu.be/vuhKjxw3lnQ
presentationVideoCaption: >-
  Thomas Hippler, président, Philippe Bonditti, secrétaire général, et Laura Lema
  Silva, responsable des études, présentent l'IPP, ses objectifs, ses méthodes de
  travail ainsi que ses axes de recherche.
