siteName: Institut pour la Paix
tagline: La paix comme objet d'étude
description: >
  L'Institut pour la Paix est un centre de recherche consacré à l'étude de la paix,
  des conflits et des dynamiques de résolution non-violente.
email: contact@institutpourlapaix.org
